ALTER TABLE USERS MODIFY FIRSTNAME VARCHAR(15) NOT NULL;

ALTER TABLE CARD_DETAILS ADD CONSTRAINT UQ_CARD_NO UNIQUE (CARD_NO);

ALTER TABLE ADS ADD CONSTRAINT AD_PRODUCT_FK 
FOREIGN KEY (P_ID) REFERENCES PRODUCT (P_ID) ON DELETE CASCADE;

ALTER TABLE PRODUCT
ADD CONSTRAINT CHECK_PRICE CHECK (PRICE >= 0);



