--TRIGGER INCREASE VIEWCOUNT ON DISPLAY OF AD

CREATE OR REPLACE TRIGGER increase_viewcount
AFTER UPDATE OF VIEWS ON ADS
FOR EACH ROW
BEGIN
    UPDATE PRODUCT SET VIEWS = VIEWS + 1 WHERE P_ID = :NEW.P_ID;
END;
